import '../styles/global.css'
import Navigation from '../components/navigation'

export const metadata = {
    title: {
        template: '%s | Next Movies',
        default: 'empty',
    },
    description: 'Generated by Next.js',
}

export default function Layout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body>
              <Navigation />
                  {children}
            </body>
        </html>
    )
}
